#version 450 core
layout(local_size_x = 64) in;

#define MAX_BATCHES 64

struct AABB {vec3 min; float padding1; vec3 max; float padding2;};

// ===== 버퍼 =====
layout(std430, binding = 0) readonly buffer TransformBuffer {mat4 transforms[];};
layout(std430, binding = 1) readonly buffer FrustumPassedBuffer {int frustumPassedIndices[];};
layout(std430, binding = 2) readonly buffer FrustumCounterBuffer {uint frustumPassedCount;};
layout(std430, binding = 3) readonly buffer WorldAABBBuffer {AABB worldAABBs[];};
layout(std430, binding = 9) readonly buffer BatchIDBuffer {uint batchIDs[];};

layout(std430, binding = 4) buffer VisibleIndicesLOD0Buffer {int visibleIndices_LOD0[];};
layout(std430, binding = 5) buffer VisibleCountsLOD0Buffer {uint visibleCounts_LOD0[];};
layout(std430, binding = 6) buffer VisibleIndicesLOD1Buffer {int visibleIndices_LOD1[];};
layout(std430, binding = 7) buffer VisibleCountsLOD1Buffer {uint visibleCounts_LOD1[];};

// ===== Uniform =====
uniform float batchLODs[64];
uniform vec3 u_cameraPosition;
uniform int u_maxInstanceCount;

void main()
{
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= frustumPassedCount) return;
    
    int instanceIdx = frustumPassedIndices[gid];
    if (instanceIdx < 0 || instanceIdx >= u_maxInstanceCount) return;
    
    uint batchID = batchIDs[instanceIdx];
    if (batchID >= MAX_BATCHES) return;
    
    // ===== LOD 거리 계산 =====
    float lodDistance = batchLODs[batchID];
    
    AABB worldAABB = worldAABBs[instanceIdx];
    vec3 worldCenter = (worldAABB.min + worldAABB.max) * 0.5;
    
    float distance = length(u_cameraPosition - worldCenter);
    bool isLOD0 = (distance < lodDistance);
    
    // ===== 저장 (전역 카운터) =====
    if (isLOD0) {
        uint slot = atomicAdd(visibleCounts_LOD0[0], 1);
        if (slot < uint(u_maxInstanceCount)) {
            visibleIndices_LOD0[slot] = instanceIdx;
        }
    } else {
        uint slot = atomicAdd(visibleCounts_LOD1[0], 1);
        if (slot < uint(u_maxInstanceCount)) {
            visibleIndices_LOD1[slot] = instanceIdx;
        }
    }
}