// <auto-generated />
// 🎬 자동 스캔 기반 다중 타입 ActionEnums 생성 시스템
// ===================================
// 📄 생성 스크립트: GenerateMultiActionEnums.ps1
// 🔧 자동 감지된 타입: Bear, Bird, Donkey, Horse, Human
// ===================================
// 📁 폴더 구조 자동 스캔:
//    ../Res/Action/Bear/*.dae → BEAR_ACTION enum
//    ../Res/Action/Bird/*.dae → BIRD_ACTION enum
//    ../Res/Action/Donkey/*.dae → DONKEY_ACTION enum
//    ../Res/Action/Horse/*.dae → HORSE_ACTION enum
//    ../Res/Action/Human/*.dae → HUMAN_ACTION enum
// ===================================
// 자동생성 by GenerateMultiActionEnums.ps1: 2025-09-22 06:32:38

using System;
using System.Linq;
using System.Collections.Generic;

namespace AutoGenEnums
{
    // ==================== 공통 인터페이스 ====================
    
    public interface IActionEnum
    {
        int GetValue();
        string GetName();
        bool IsCommonAction();
    }
    // ==================== BEAR ACTIONS ====================
    
    public static class BearActions
    {
        public static Dictionary<BEAR_ACTION, string> ActionMap = new Dictionary<BEAR_ACTION, string>()
        {
            {BEAR_ACTION.IDLE, "Idle"},
            {BEAR_ACTION.RUN, "Run"},
        };

        public static string GetRandomAction() => ActionMap.Values.ElementAt(new Random().Next(ActionMap.Count));
        public static int Count => 2;
        public static bool HasAction(BEAR_ACTION action) => ActionMap.ContainsKey(action);
        public static string GetActionName(BEAR_ACTION action) => ActionMap.TryGetValue(action, out string name) ? name : null;
    }

    public enum BEAR_ACTION : int
    {
        IDLE = 0,
        RUN = 1,
        // 추가된 액션들
        RANDOM,
        STOP,
        NONE,
        COUNT,
    }
    // ==================== BIRD ACTIONS ====================
    
    public static class BirdActions
    {
        public static Dictionary<BIRD_ACTION, string> ActionMap = new Dictionary<BIRD_ACTION, string>()
        {
            {BIRD_ACTION.FLY, "Fly"},
            {BIRD_ACTION.WALK, "Walk"},
        };

        public static string GetRandomAction() => ActionMap.Values.ElementAt(new Random().Next(ActionMap.Count));
        public static int Count => 2;
        public static bool HasAction(BIRD_ACTION action) => ActionMap.ContainsKey(action);
        public static string GetActionName(BIRD_ACTION action) => ActionMap.TryGetValue(action, out string name) ? name : null;
    }

    public enum BIRD_ACTION : int
    {
        FLY = 0,
        WALK = 1,
        // 추가된 액션들
        RANDOM,
        STOP,
        NONE,
        COUNT,
    }
    // ==================== DONKEY ACTIONS ====================
    
    public static class DonkeyActions
    {
        public static Dictionary<DONKEY_ACTION, string> ActionMap = new Dictionary<DONKEY_ACTION, string>()
        {
            {DONKEY_ACTION.A_T_POSE, "a-T-Pose"},
            {DONKEY_ACTION.H_AMBLE, "H_Amble"},
            {DONKEY_ACTION.H_ATTACK_BACK_LEGS, "H_Attack_Back_Legs"},
            {DONKEY_ACTION.H_ATTACK_FRONT_LEGS, "H_Attack_Front_Legs"},
            {DONKEY_ACTION.H_CANTER, "H_Canter"},
            {DONKEY_ACTION.H_CANTER_RIGHT, "H_Canter_Right"},
            {DONKEY_ACTION.H_DEATH01, "H_Death01"},
            {DONKEY_ACTION.H_DRINK, "H_Drink"},
            {DONKEY_ACTION.H_IDLE, "H_Idle"},
            {DONKEY_ACTION.H_NEIGH, "H_Neigh"},
            {DONKEY_ACTION.H_SLEEP, "H_Sleep"},
        };

        public static string GetRandomAction() => ActionMap.Values.ElementAt(new Random().Next(ActionMap.Count));
        public static int Count => 11;
        public static bool HasAction(DONKEY_ACTION action) => ActionMap.ContainsKey(action);
        public static string GetActionName(DONKEY_ACTION action) => ActionMap.TryGetValue(action, out string name) ? name : null;
    }

    public enum DONKEY_ACTION : int
    {
        A_T_POSE = 0,
        H_AMBLE = 1,
        H_ATTACK_BACK_LEGS = 2,
        H_ATTACK_FRONT_LEGS = 3,
        H_CANTER = 4,
        H_CANTER_RIGHT = 5,
        H_DEATH01 = 6,
        H_DRINK = 7,
        H_IDLE = 8,
        H_NEIGH = 9,
        H_SLEEP = 10,
        // 추가된 액션들
        RANDOM,
        STOP,
        NONE,
        COUNT,
    }
    // ==================== HORSE ACTIONS ====================
    
    public static class HorseActions
    {
        public static Dictionary<HORSE_ACTION, string> ActionMap = new Dictionary<HORSE_ACTION, string>()
        {
            {HORSE_ACTION.ABC, "abc"},
            {HORSE_ACTION.ASEAT, "aSeat"},
            {HORSE_ACTION.CDE, "cde"},
        };

        public static string GetRandomAction() => ActionMap.Values.ElementAt(new Random().Next(ActionMap.Count));
        public static int Count => 3;
        public static bool HasAction(HORSE_ACTION action) => ActionMap.ContainsKey(action);
        public static string GetActionName(HORSE_ACTION action) => ActionMap.TryGetValue(action, out string name) ? name : null;
    }

    public enum HORSE_ACTION : int
    {
        ABC = 0,
        ASEAT = 1,
        CDE = 2,
        // 추가된 액션들
        RANDOM,
        STOP,
        NONE,
        COUNT,
    }
    // ==================== HUMAN ACTIONS ====================
    
    public static class HumanActions
    {
        public static Dictionary<HUMAN_ACTION, string> ActionMap = new Dictionary<HUMAN_ACTION, string>()
        {
            {HUMAN_ACTION.A_T_POSE, "a-T-Pose"},
            {HUMAN_ACTION.ANNOYED_HEAD_SHAKE, "Annoyed Head Shake"},
            {HUMAN_ACTION.BREATHING_IDLE, "Breathing Idle"},
            {HUMAN_ACTION.CAPOEIRA, "Capoeira"},
            {HUMAN_ACTION.DEFEATED, "Defeated"},
            {HUMAN_ACTION.DYING, "Dying"},
            {HUMAN_ACTION.GUNPLAY, "Gunplay"},
            {HUMAN_ACTION.JUMP, "Jump"},
            {HUMAN_ACTION.WALKING, "Walking"},
        };

        public static string GetRandomAction() => ActionMap.Values.ElementAt(new Random().Next(ActionMap.Count));
        public static int Count => 9;
        public static bool HasAction(HUMAN_ACTION action) => ActionMap.ContainsKey(action);
        public static string GetActionName(HUMAN_ACTION action) => ActionMap.TryGetValue(action, out string name) ? name : null;
    }

    public enum HUMAN_ACTION : int
    {
        A_T_POSE = 0,
        ANNOYED_HEAD_SHAKE = 1,
        BREATHING_IDLE = 2,
        CAPOEIRA = 3,
        DEFEATED = 4,
        DYING = 5,
        GUNPLAY = 6,
        JUMP = 7,
        WALKING = 8,
        // 추가된 액션들
        RANDOM,
        STOP,
        NONE,
        COUNT,
    }
    // ==================== 확장 메서드로 인터페이스 구현 ====================
    
    public static class ActionEnumExtensions
    {
        private static readonly HashSet<string> CommonActions = new HashSet<string>
        {
            "RANDOM", "STOP", "NONE", "COUNT"
        };
        public static int GetValue(this BEAR_ACTION action) => (int)action;
        public static string GetName(this BEAR_ACTION action) => action.ToString();
        public static bool IsCommonAction(this BEAR_ACTION action) => CommonActions.Contains(action.ToString());
        public static int GetValue(this BIRD_ACTION action) => (int)action;
        public static string GetName(this BIRD_ACTION action) => action.ToString();
        public static bool IsCommonAction(this BIRD_ACTION action) => CommonActions.Contains(action.ToString());
        public static int GetValue(this DONKEY_ACTION action) => (int)action;
        public static string GetName(this DONKEY_ACTION action) => action.ToString();
        public static bool IsCommonAction(this DONKEY_ACTION action) => CommonActions.Contains(action.ToString());
        public static int GetValue(this HORSE_ACTION action) => (int)action;
        public static string GetName(this HORSE_ACTION action) => action.ToString();
        public static bool IsCommonAction(this HORSE_ACTION action) => CommonActions.Contains(action.ToString());
        public static int GetValue(this HUMAN_ACTION action) => (int)action;
        public static string GetName(this HUMAN_ACTION action) => action.ToString();
        public static bool IsCommonAction(this HUMAN_ACTION action) => CommonActions.Contains(action.ToString());    }
    // ==================== 동적 액션 유틸리티 ====================
    
    public static class ActionUtils
    {
        // 모든 타입의 액션 개수
        public static int TotalActionCount => BearActions.Count + BirdActions.Count + DonkeyActions.Count + HorseActions.Count + HumanActions.Count;
        
        // 감지된 액션 타입들
        public static readonly string[] DetectedActionTypes = { "Bear", "Bird", "Donkey", "Horse", "Human" };
        
        // 타입별 액션 통계
        public static void PrintActionStats()
        {
            System.Console.WriteLine("=== Auto-Detected Action Statistics ===");            System.Console.WriteLine("Bear Actions: {0}", BearActions.Count);            System.Console.WriteLine("Bird Actions: {0}", BirdActions.Count);            System.Console.WriteLine("Donkey Actions: {0}", DonkeyActions.Count);            System.Console.WriteLine("Horse Actions: {0}", HorseActions.Count);            System.Console.WriteLine("Human Actions: {0}", HumanActions.Count);            System.Console.WriteLine("Total Actions: {0}", TotalActionCount);
            System.Console.WriteLine("Detected Types: {0}", string.Join(", ", DetectedActionTypes));
        }
        
        // 동적 랜덤 액션 가져오기        public static string GetRandomBearAction() => BearActions.GetRandomAction();        public static string GetRandomBirdAction() => BirdActions.GetRandomAction();        public static string GetRandomDonkeyAction() => DonkeyActions.GetRandomAction();        public static string GetRandomHorseAction() => HorseActions.GetRandomAction();        public static string GetRandomHumanAction() => HumanActions.GetRandomAction();        
        // 타입명으로 랜덤 액션 가져오기 (동적)
        public static string GetRandomActionByType(string typeName)
        {
            switch (typeName?.ToLower())
            {                case "bear":
                    return BearActions.GetRandomAction();                case "bird":
                    return BirdActions.GetRandomAction();                case "donkey":
                    return DonkeyActions.GetRandomAction();                case "horse":
                    return HorseActions.GetRandomAction();                case "human":
                    return HumanActions.GetRandomAction();                default:
                    throw new ArgumentException($"Unknown action type: {typeName}. Available types: {string.Join(", ", DetectedActionTypes)}");
            }
        }
    }
}