// <auto-generated />
// 🎬 ActionEnums 자동 생성 시스템
// ===================================
// 📄 생성 스크립트: GenerateActions.ps1 (ActionEnums 프로젝트 폴더에 위치)
// 🔧 실행 방법:
//    1) 자동: 빌드할 때 .csproj의 BeforeTargets로 자동 실행
//    2) 수동: PowerShell에서 .\GenerateActions.ps1 직접 실행
// ===================================
// 📁 파일명 변환 규칙:
//    "a-T-Pose.dae" → A_T_POSE = "a-T-Pose"
//    "Breathing Idle.dae" → BREATHING_IDLE = "Breathing Idle"  
//    "Fast Run.dae" → FAST_RUN = "Fast Run"
// ===================================
// 1. Assets/Action/ 폴더의 .dae 파일들 스캔
// 2. GenerateActions.ps1이 파일명을 C# 상수로 변환
// 3. 빌드 시 자동으로 이 파일 생성됨
// 4. 메인 프로젝트에서 Actions.WALKING 같이 IntelliSense로 사용!
// ===================================
// 자동생성 by GenerateActions.ps1: 2025-06-24 16:10:50
// .ps1 = PowerShell 스크립트 파일의 표준 확장자입니다! 🚀

using System;
using System.Linq;
using System.Collections.Generic;

namespace AutoGenEnums
{
    public static class Actions
    {
        public static Dictionary<ACTION, string> ActionMap = new Dictionary<ACTION, string>()
        {
			{ACTION.A_T_POSE, "a-T-Pose"},
			{ACTION.AXE_ATTACK_DOWNWARD, "Axe Attack Downward"},
			{ACTION.AXE_STANDING_IDLE, "Axe Standing Idle"},
			{ACTION.BREATHING_IDLE, "Breathing Idle"},
			{ACTION.FAST_RUN, "Fast Run"},
			{ACTION.GUNPLAY, "Gunplay"},
			{ACTION.INTERPOLATION_POSE, "Interpolation Pose"},
			{ACTION.JUMP, "Jump"},
			{ACTION.LEFT_STRAFE_WALK, "Left Strafe Walk"},
			{ACTION.RIGHT_STRAFE_WALK, "Right Strafe Walk"},
			{ACTION.RUNNING, "Running"},
			{ACTION.SLOW_RUN, "Slow Run"},
			{ACTION.STANDING_IDLE, "Standing Idle"},
			{ACTION.WALKING, "Walking"},
			{ACTION.WALKING_BACKWARDS, "Walking Backwards"},
		};

        public static string GetRandomAction() => ActionMap.Values.ElementAt(new Random().Next(ActionMap.Count));
        public static int Count => 15;
    }

    public enum ACTION
    {
        A_T_POSE = 0,
        AXE_ATTACK_DOWNWARD = 1,
        AXE_STANDING_IDLE = 2,
        BREATHING_IDLE = 3,
        FAST_RUN = 4,
        GUNPLAY = 5,
        INTERPOLATION_POSE = 6,
        JUMP = 7,
        LEFT_STRAFE_WALK = 8,
        RIGHT_STRAFE_WALK = 9,
        RUNNING = 10,
        SLOW_RUN = 11,
        STANDING_IDLE = 12,
        WALKING = 13,
        WALKING_BACKWARDS = 14,
        // 추가된 액션들
		RANDOM,
        STOP,
		NONE,
		COUNT,
    }
}