// <auto-generated />
// 🎬 다중 타입 ActionEnums 자동 생성 시스템
// ===================================
// 📄 생성 스크립트: GenerateMultiActionEnums.ps1
// 🔧 지원 타입: Human, Horse (확장 가능)
// ===================================
// 📁 폴더 구조:
//    ../Res/Action/Human/*.dae → HUMAN_ACTION enum
//    ../Res/Action/Horse/*.dae → HORSE_ACTION enum
// ===================================
// 자동생성 by GenerateMultiActionEnums.ps1: 2025-08-11 23:21:06

using System;
using System.Linq;
using System.Collections.Generic;

namespace AutoGenEnums
{
    // ==================== HUMAN ACTIONS ====================
    
    public static class HumanActions
    {
        public static Dictionary<HUMAN_ACTION, string> ActionMap = new Dictionary<HUMAN_ACTION, string>()
        {
            {HUMAN_ACTION.A_T_POSE, "a-T-Pose"},
            {HUMAN_ACTION.ANNOYED_HEAD_SHAKE, "Annoyed Head Shake"},
            {HUMAN_ACTION.BREATHING_IDLE, "Breathing Idle"},
            {HUMAN_ACTION.CAPOEIRA, "Capoeira"},
            {HUMAN_ACTION.DEFEATED, "Defeated"},
            {HUMAN_ACTION.DYING, "Dying"},
            {HUMAN_ACTION.GUNPLAY, "Gunplay"},
            {HUMAN_ACTION.WALKING, "Walking"},
        };

        public static string GetRandomAction() => ActionMap.Values.ElementAt(new Random().Next(ActionMap.Count));
        public static int Count => 8;
        public static bool HasAction(HUMAN_ACTION action) => ActionMap.ContainsKey(action);
        public static string GetActionName(HUMAN_ACTION action) => ActionMap.TryGetValue(action, out string name) ? name : null;
    }

    public enum HUMAN_ACTION
    {
        A_T_POSE = 0,
        ANNOYED_HEAD_SHAKE = 1,
        BREATHING_IDLE = 2,
        CAPOEIRA = 3,
        DEFEATED = 4,
        DYING = 5,
        GUNPLAY = 6,
        WALKING = 7,
        // 추가된 액션들
        RANDOM,
        STOP,
        NONE,
        COUNT,
    }
    // ==================== HORSE ACTIONS ====================
    
    public static class HorseActions
    {
        public static Dictionary<HORSE_ACTION, string> ActionMap = new Dictionary<HORSE_ACTION, string>()
        {
            {HORSE_ACTION.STAND, "Stand"},
            {HORSE_ACTION.WALK, "Walk"},
        };

        public static string GetRandomAction() => ActionMap.Values.ElementAt(new Random().Next(ActionMap.Count));
        public static int Count => 2;
        public static bool HasAction(HORSE_ACTION action) => ActionMap.ContainsKey(action);
        public static string GetActionName(HORSE_ACTION action) => ActionMap.TryGetValue(action, out string name) ? name : null;
    }

    public enum HORSE_ACTION
    {
        STAND = 0,
        WALK = 1,
        // 추가된 액션들
        RANDOM,
        STOP,
        NONE,
        COUNT,
    }
    // ==================== 통합 ACTIONS 관리 ====================
    
    public static class Actions
    {
        // 하위 호환성을 위한 Human Actions 직접 접근
        public static Dictionary<HUMAN_ACTION, string> ActionMap => HumanActions.ActionMap;
        public static string GetRandomAction() => HumanActions.GetRandomAction();
        public static int Count => HumanActions.Count;
        
        // 모든 타입의 액션 개수
        public static int TotalActionCount => HumanActions.Count + HorseActions.Count;
        
        // 타입별 액션 존재 여부 확인
        public static bool HasHumanAction(HUMAN_ACTION action) => HumanActions.HasAction(action);        public static bool HasHorseAction(HORSE_ACTION action) => HorseActions.HasAction(action);    }
}