# GenerateActions.ps1 - ActionEnums 프로젝트 폴더에 저장
param(
    [string]$ActionPath = "..\Res\Action",  # 액션 폴더 경로
    [string]$OutputFile = "ActionEnums.cs"     # 출력 파일
)

Write-Host "🎬 Generating ActionEnums.cs..." -ForegroundColor Green

# 액션 폴더 확인
if (!(Test-Path $ActionPath)) {
    Write-Warning "Action folder not found: $ActionPath"
    Write-Host "Creating empty ActionEnums.cs" -ForegroundColor Yellow
    
    $emptyCode = @"
// <auto-generated />
// .ps1 = PowerShell 스크립트 파일의 표준 확장자입니다! 🚀
using System;
using System.Linq;

namespace AutoGenEnums
{
    public static class Actions
    {
        public static readonly string[] All = new string[0];
        public static bool Contains(string action) => false;
        public static string Random() => throw new InvalidOperationException("No Actions available");
        public static int Count => 0;
    }

    public enum ACTION
    {
        COUNT = 0
    }
}
"@
    
    [System.IO.File]::WriteAllText($OutputFile, $emptyCode, [System.Text.Encoding]::UTF8)
    return
}

# .dae 파일들 스캔
$daeFiles = Get-ChildItem -Path $ActionPath -Filter "*.dae"
Write-Host "Found $($daeFiles.Count) .dae files" -ForegroundColor Cyan

if ($daeFiles.Count -eq 0) {
    Write-Warning "No .dae files found"
    return
}

# 액션 정보 생성
$actions = @()
foreach ($file in $daeFiles) {
    $originalName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $enumName = $originalName.ToUpper() -replace '[-\s]', '_'
    
    $actions += @{
        Original = $originalName
        Enum = $enumName
    }
    
    Write-Host "  ✓ $originalName → $enumName" -ForegroundColor White
}

# 정렬
$actions = $actions | Sort-Object { $_.Enum }

# C# 코드 생성
$code = @"
// <auto-generated />
// 🎬 ActionEnums 자동 생성 시스템
// ===================================
// 📄 생성 스크립트: GenerateActions.ps1 (ActionEnums 프로젝트 폴더에 위치)
// 🔧 실행 방법:
//    1) 자동: 빌드할 때 .csproj의 BeforeTargets로 자동 실행
//    2) 수동: PowerShell에서 .\GenerateActions.ps1 직접 실행
// ===================================
// 📁 파일명 변환 규칙:
//    "a-T-Pose.dae" → A_T_POSE = "a-T-Pose"
//    "Breathing Idle.dae" → BREATHING_IDLE = "Breathing Idle"  
//    "Fast Run.dae" → FAST_RUN = "Fast Run"
// ===================================
// 1. Assets/Action/ 폴더의 .dae 파일들 스캔
// 2. GenerateActions.ps1이 파일명을 C# 상수로 변환
// 3. 빌드 시 자동으로 이 파일 생성됨
// 4. 메인 프로젝트에서 Actions.WALKING 같이 IntelliSense로 사용!
// ===================================
// 자동생성 by GenerateActions.ps1: 2025-06-24 16:10:50
// .ps1 = PowerShell 스크립트 파일의 표준 확장자입니다! 🚀

using System;
using System.Linq;

namespace AutoGenEnums
{
    public static class Actions
    {
"@

# 상수 정의
foreach ($action in $actions) {
    $code += "`n        public const string $($action.Enum) = `"$($action.Original)`";"
}

# All 배열
$code += "`n`n        public static readonly string[] All = { "
$code += ($actions | ForEach-Object { $_.Enum }) -join ", "
$code += " };"

# 메서드들
$code += @"

        public static bool Contains(string action) => All.Contains(action);
        public static string Random() => All[new Random().Next(All.Length)];
        public static int Count => $($actions.Count);
    }

    public enum ACTION
    {
"@

# enum 멤버들
for ($i = 0; $i -lt $actions.Count; $i++) {
    $comma = if ($i -lt $actions.Count - 1) { "," } else { "," }
    $code += "`n        $($actions[$i].Enum) = $i$comma"
}

$code += @"

        STOP,    
		COUNT,
    }
}
"@

# 파일 저장
[System.IO.File]::WriteAllText($OutputFile, $code, [System.Text.Encoding]::UTF8)

Write-Host "✅ Generated $($actions.Count) actions in $OutputFile" -ForegroundColor Green