# GenerateMultiActionEnums.ps1 - 자동 폴더 스캔 기반 다중 액션 타입 지원
param(
    [string]$ActionBasePath = "..\Res\Action",  # 기본 액션 폴더
    [string]$OutputFile = "ActionEnums.cs"     # 출력 파일
)

Write-Host "🎬 Generating Auto-Scanned Multi-Type ActionEnums.cs..." -ForegroundColor Green

# ActionBasePath에서 폴더들을 자동으로 스캔하여 액션 타입 생성
function Get-ActionTypesFromFolders {
    param([string]$BasePath)
    
    $actionTypes = @()
    
    if (-not (Test-Path $BasePath)) {
        Write-Warning "⚠️  Base path not found: $BasePath"
        return $actionTypes
    }
    
    Write-Host "📁 Scanning action folders in: $BasePath" -ForegroundColor Cyan
    
    $folders = Get-ChildItem -Path $BasePath -Directory
    
    foreach ($folder in $folders) {
        $folderName = $folder.Name
        
        # _로 시작하는 폴더는 제외
        if ($folderName.StartsWith("_")) {
            Write-Host "   ⚫ Skipped: $folderName (starts with _)" -ForegroundColor DarkGray
            continue
        }
        
        $enumName = $folderName.ToUpper() + "_ACTION"
        
        # .dae 파일이 있는 폴더만 유효한 액션 타입으로 간주
        $daeFiles = Get-ChildItem -Path $folder.FullName -Filter "*.dae"
        
        if ($daeFiles.Count -gt 0) {
            $actionTypes += @{
                Name = $folderName
                Folder = $folderName
                EnumName = $enumName
            }
            
            Write-Host "   ✓ Found action type: $folderName ($($daeFiles.Count) actions) → $enumName" -ForegroundColor Green
        } else {
            Write-Host "   ⚪ Skipped: $folderName (no .dae files)" -ForegroundColor Gray
        }
    }
    
    if ($actionTypes.Count -eq 0) {
        Write-Warning "⚠️  No valid action types found in $BasePath"
    } else {
        Write-Host "🎯 Total action types found: $($actionTypes.Count)" -ForegroundColor Yellow
    }
    
    return $actionTypes
}

# 자동으로 액션 타입들 생성
$ActionTypes = Get-ActionTypesFromFolders -BasePath $ActionBasePath

if ($ActionTypes.Count -eq 0) {
    Write-Error "❌ No action types found. Please check the folder structure."
    exit 1
}

# 각 타입별 액션 수집
$AllActionTypes = @()

foreach ($actionType in $ActionTypes) {
    $actionPath = Join-Path $ActionBasePath $actionType.Folder
    $actions = @()
    
    Write-Host "📁 Scanning $($actionType.Name) actions in: $actionPath" -ForegroundColor Cyan
    
    if (Test-Path $actionPath) {
        $daeFiles = Get-ChildItem -Path $actionPath -Filter "*.dae"
        Write-Host "   Found $($daeFiles.Count) .dae files" -ForegroundColor White
        
        foreach ($file in $daeFiles) {
            $originalName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
            $enumName = $originalName.ToUpper() -replace '[-\s]', '_'
            
            $actions += @{
                Original = $originalName
                Enum = $enumName
            }
            
            Write-Host "     ✓ $originalName → $enumName" -ForegroundColor Gray
        }
        
        # 정렬
        $actions = $actions | Sort-Object { $_.Enum }
    } else {
        Write-Warning "   Folder not found: $actionPath"
    }
    
    $AllActionTypes += @{
        Type = $actionType
        Actions = $actions
    }
}

# C# 코드 생성 시작
$supportedTypes = ($ActionTypes | ForEach-Object { $_.Name }) -join ", "

$code = @"
// <auto-generated />
// 🎬 자동 스캔 기반 다중 타입 ActionEnums 생성 시스템
// ===================================
// 📄 생성 스크립트: GenerateMultiActionEnums.ps1
// 🔧 자동 감지된 타입: $supportedTypes
// ===================================
// 📁 폴더 구조 자동 스캔:
"@

foreach ($actionType in $ActionTypes) {
    $code += "`n//    ../Res/Action/$($actionType.Folder)/*.dae → $($actionType.EnumName) enum"
}

$code += @"

// ===================================
// 자동생성 by GenerateMultiActionEnums.ps1: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

using System;
using System.Linq;
using System.Collections.Generic;

namespace AutoGenEnums
{
    // ==================== 공통 인터페이스 ====================
    
    public interface IActionEnum
    {
        int GetValue();
        string GetName();
        bool IsCommonAction();
    }
"@

# 각 타입별로 enum과 매핑 생성
foreach ($actionTypeData in $AllActionTypes) {
    $actionType = $actionTypeData.Type
    $actions = $actionTypeData.Actions
    
    if ($actions.Count -eq 0) {
        continue
    }
    
    $code += @"

    // ==================== $($actionType.Name.ToUpper()) ACTIONS ====================
    
    public static class $($actionType.Name)Actions
    {
        public static Dictionary<$($actionType.EnumName), string> ActionMap = new Dictionary<$($actionType.EnumName), string>()
        {
"@

    # Dictionary 항목들
    foreach ($action in $actions) {
        $code += "`n            {$($actionType.EnumName).$($action.Enum), `"$($action.Original)`"},"
    }
    
    $code += @"

        };

        public static string GetRandomAction() => ActionMap.Values.ElementAt(new Random().Next(ActionMap.Count));
        public static int Count => $($actions.Count);
        public static bool HasAction($($actionType.EnumName) action) => ActionMap.ContainsKey(action);
        public static string GetActionName($($actionType.EnumName) action) => ActionMap.TryGetValue(action, out string name) ? name : null;
    }

    public enum $($actionType.EnumName) : int
    {
"@
    # enum 멤버들
    for ($i = 0; $i -lt $actions.Count; $i++) {
        $comma = if ($i -lt $actions.Count - 1) { "," } else { "," }
        $code += "`n        $($actions[$i].Enum) = $i$comma"
    }

    $code += @"

        // 추가된 액션들
        RANDOM,
        STOP,
        NONE,
        COUNT,
    }
"@
}

# ActionEnumExtensions 클래스 추가
$code += @"

    // ==================== 확장 메서드로 인터페이스 구현 ====================
    
    public static class ActionEnumExtensions
    {
        private static readonly HashSet<string> CommonActions = new HashSet<string>
        {
            "RANDOM", "STOP", "NONE", "COUNT"
        };
"@

# 각 액션 타입에 대한 확장 메서드 생성
foreach ($actionTypeData in $AllActionTypes) {
    if ($actionTypeData.Actions.Count -eq 0) {
        continue
    }
    
    $enumName = $actionTypeData.Type.EnumName
    $code += @"

        public static int GetValue(this $enumName action) => (int)action;
        public static string GetName(this $enumName action) => action.ToString();
        public static bool IsCommonAction(this $enumName action) => CommonActions.Contains(action.ToString());
"@
}

$code += @"
    }
"@

# 동적 유틸리티 클래스 추가
$code += @"

    // ==================== 동적 액션 유틸리티 ====================
    
    public static class ActionUtils
    {
        // 모든 타입의 액션 개수
        public static int TotalActionCount => 
"@

$totalCountExpression = ($AllActionTypes | Where-Object { $_.Actions.Count -gt 0 } | ForEach-Object { "$($_.Type.Name)Actions.Count" }) -join " + "
if ([string]::IsNullOrEmpty($totalCountExpression)) {
    $totalCountExpression = "0"
}

$code += @"
$totalCountExpression;
        
        // 감지된 액션 타입들
        public static readonly string[] DetectedActionTypes = { $((($ActionTypes | ForEach-Object { "`"$($_.Name)`"" }) -join ", ")) };
        
        // 타입별 액션 통계
        public static void PrintActionStats()
        {
            System.Console.WriteLine("=== Auto-Detected Action Statistics ===");
"@

foreach ($actionTypeData in $AllActionTypes) {
    if ($actionTypeData.Actions.Count -gt 0) {
        $typeName = $actionTypeData.Type.Name
        $code += @"
            System.Console.WriteLine(`"$typeName Actions: {0}`", $($typeName)Actions.Count);
"@
    }
}

$code += @"
            System.Console.WriteLine(`"Total Actions: {0}`", TotalActionCount);
            System.Console.WriteLine(`"Detected Types: {0}`", string.Join(`", `", DetectedActionTypes));
        }
        
        // 동적 랜덤 액션 가져오기
"@

# 각 타입별 랜덤 액션 메서드 동적 생성
foreach ($actionTypeData in $AllActionTypes) {
    if ($actionTypeData.Actions.Count -gt 0) {
        $typeName = $actionTypeData.Type.Name
        $code += @"
        public static string GetRandom$($typeName)Action() => $($typeName)Actions.GetRandomAction();
"@
    }
}

# 타입명으로 랜덤 액션 가져오는 범용 메서드
$code += @"
        
        // 타입명으로 랜덤 액션 가져오기 (동적)
        public static string GetRandomActionByType(string typeName)
        {
            switch (typeName?.ToLower())
            {
"@

foreach ($actionTypeData in $AllActionTypes) {
    if ($actionTypeData.Actions.Count -gt 0) {
        $typeName = $actionTypeData.Type.Name
        $code += @"
                case "$($typeName.ToLower())":
                    return $($typeName)Actions.GetRandomAction();
"@
    }
}

$code += @"
                default:
                    throw new ArgumentException(`$"Unknown action type: {typeName}. Available types: {string.Join(`", `", DetectedActionTypes)}`");
            }
        }
    }
}
"@

# 파일 저장
[System.IO.File]::WriteAllText($OutputFile, $code, [System.Text.Encoding]::UTF8)

Write-Host "✅ Generated auto-scanned multi-type ActionEnums.cs:" -ForegroundColor Green
foreach ($actionTypeData in $AllActionTypes) {
    if ($actionTypeData.Actions.Count -gt 0) {
        Write-Host "   $($actionTypeData.Type.Name): $($actionTypeData.Actions.Count) actions" -ForegroundColor Yellow
    } else {
        Write-Host "   $($actionTypeData.Type.Name): No actions found" -ForegroundColor Gray
    }
}
$totalActions = ($AllActionTypes | ForEach-Object { $_.Actions.Count } | Measure-Object -Sum).Sum
Write-Host "   Total: $totalActions actions across $($ActionTypes.Count) types" -ForegroundColor Green

# 생성된 클래스들 요약
$generatedClasses = @()
foreach ($actionType in $ActionTypes) {
    $generatedClasses += "$($actionType.Name)Actions"
}
$generatedClasses += @("ActionEnumExtensions", "ActionUtils")

Write-Host "🎯 Classes generated: $($generatedClasses -join ', ')" -ForegroundColor Magenta
Write-Host "🔄 Script will automatically adapt to new folders added to $ActionBasePath" -ForegroundColor Cyan