# GenerateMultiActionEnums.ps1 - 다중 액션 타입 지원
param(
    [string]$ActionBasePath = "..\Res\Action",  # 기본 액션 폴더
    [string]$OutputFile = "ActionEnums.cs"     # 출력 파일
)

Write-Host "🎬 Generating Multi-Type ActionEnums.cs..." -ForegroundColor Green

# 지원할 액션 타입들 정의
$ActionTypes = @(
    @{ Name = "Human"; Folder = "Human"; EnumName = "HUMAN_ACTION" },
    @{ Name = "Horse"; Folder = "Horse"; EnumName = "HORSE_ACTION" }
)

# 각 타입별 액션 수집
$AllActionTypes = @()

foreach ($actionType in $ActionTypes) {
    $actionPath = Join-Path $ActionBasePath $actionType.Folder
    $actions = @()
    
    Write-Host "📁 Scanning $($actionType.Name) actions in: $actionPath" -ForegroundColor Cyan
    
    if (Test-Path $actionPath) {
        $daeFiles = Get-ChildItem -Path $actionPath -Filter "*.dae"
        Write-Host "   Found $($daeFiles.Count) .dae files" -ForegroundColor White
        
        foreach ($file in $daeFiles) {
            $originalName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
            $enumName = $originalName.ToUpper() -replace '[-\s]', '_'
            
            $actions += @{
                Original = $originalName
                Enum = $enumName
            }
            
            Write-Host "     ✓ $originalName → $enumName" -ForegroundColor Gray
        }
        
        # 정렬
        $actions = $actions | Sort-Object { $_.Enum }
    } else {
        Write-Warning "   Folder not found: $actionPath"
    }
    
    $AllActionTypes += @{
        Type = $actionType
        Actions = $actions
    }
}

# C# 코드 생성 시작
$code = @"
// <auto-generated />
// 🎬 다중 타입 ActionEnums 자동 생성 시스템
// ===================================
// 📄 생성 스크립트: GenerateMultiActionEnums.ps1
// 🔧 지원 타입: Human, Horse (확장 가능)
// ===================================
// 📁 폴더 구조:
//    ../Res/Action/Human/*.dae → HUMAN_ACTION enum
//    ../Res/Action/Horse/*.dae → HORSE_ACTION enum
// ===================================
// 자동생성 by GenerateMultiActionEnums.ps1: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

using System;
using System.Linq;
using System.Collections.Generic;

namespace AutoGenEnums
{
    // ==================== 공통 인터페이스 ====================
    
    public interface IActionEnum
    {
        int GetValue();
        string GetName();
        bool IsCommonAction();
    }
"@

# 각 타입별로 enum과 매핑 생성
foreach ($actionTypeData in $AllActionTypes) {
    $actionType = $actionTypeData.Type
    $actions = $actionTypeData.Actions
    
    if ($actions.Count -eq 0) {
        continue
    }
    
    $code += @"

    // ==================== $($actionType.Name.ToUpper()) ACTIONS ====================
    
    public static class $($actionType.Name)Actions
    {
        public static Dictionary<$($actionType.EnumName), string> ActionMap = new Dictionary<$($actionType.EnumName), string>()
        {
"@

    # Dictionary 항목들
    foreach ($action in $actions) {
        $code += "`n            {$($actionType.EnumName).$($action.Enum), `"$($action.Original)`"},"
    }
    
    $code += @"

        };

        public static string GetRandomAction() => ActionMap.Values.ElementAt(new Random().Next(ActionMap.Count));
        public static int Count => $($actions.Count);
        public static bool HasAction($($actionType.EnumName) action) => ActionMap.ContainsKey(action);
        public static string GetActionName($($actionType.EnumName) action) => ActionMap.TryGetValue(action, out string name) ? name : null;
    }

    public enum $($actionType.EnumName) : int
    {
"@
    # enum 멤버들
    for ($i = 0; $i -lt $actions.Count; $i++) {
        $comma = if ($i -lt $actions.Count - 1) { "," } else { "," }
        $code += "`n        $($actions[$i].Enum) = $i$comma"
    }

    $code += @"

        // 추가된 액션들
        RANDOM,
        STOP,
        NONE,
        COUNT,
    }
"@
}

# ActionEnumExtensions 클래스 추가
$code += @"

    // ==================== 확장 메서드로 인터페이스 구현 ====================
    
    public static class ActionEnumExtensions
    {
        private static readonly HashSet<string> CommonActions = new HashSet<string>
        {
            "RANDOM", "STOP", "NONE", "COUNT"
        };
"@

# 각 액션 타입에 대한 확장 메서드 생성
foreach ($actionTypeData in $AllActionTypes) {
    if ($actionTypeData.Actions.Count -eq 0) {
        continue
    }
    
    $enumName = $actionTypeData.Type.EnumName
    $code += @"

        public static int GetValue(this $enumName action) => (int)action;
        public static string GetName(this $enumName action) => action.ToString();
        public static bool IsCommonAction(this $enumName action) => CommonActions.Contains(action.ToString());
"@
}

$code += @"
    }
"@

# 유틸리티 클래스 추가 (Actions 대신)
$code += @"

    // ==================== 액션 유틸리티 ====================
    
    public static class ActionUtils
    {
        // 모든 타입의 액션 개수
        public static int TotalActionCount => 
"@

$totalCountExpression = ($AllActionTypes | Where-Object { $_.Actions.Count -gt 0 } | ForEach-Object { "$($_.Type.Name)Actions.Count" }) -join " + "
if ([string]::IsNullOrEmpty($totalCountExpression)) {
    $totalCountExpression = "0"
}

$code += @"
$totalCountExpression;
        
        // 타입별 액션 통계
        public static void PrintActionStats()
        {
            System.Console.WriteLine("=== Action Statistics ===");
"@

foreach ($actionTypeData in $AllActionTypes) {
    if ($actionTypeData.Actions.Count -gt 0) {
        $typeName = $actionTypeData.Type.Name
        $code += @"
            System.Console.WriteLine(`"$typeName Actions: {0}`", $($typeName)Actions.Count);
"@
    }
}

$code += @"
            System.Console.WriteLine(`"Total Actions: {0}`", TotalActionCount);
        }
        
        // 특정 타입의 랜덤 액션 가져오기
        public static string GetRandomHumanAction() => HumanActions.GetRandomAction();
"@

# Horse가 있다면 Horse 랜덤 액션도 추가
if (($AllActionTypes | Where-Object { $_.Type.Name -eq "Horse" -and $_.Actions.Count -gt 0 }).Count -gt 0) {
    $code += @"
        public static string GetRandomHorseAction() => HorseActions.GetRandomAction();
"@
}

$code += @"
    }
}
"@

# 파일 저장
[System.IO.File]::WriteAllText($OutputFile, $code, [System.Text.Encoding]::UTF8)

Write-Host "✅ Generated multi-type ActionEnums.cs:" -ForegroundColor Green
foreach ($actionTypeData in $AllActionTypes) {
    if ($actionTypeData.Actions.Count -gt 0) {
        Write-Host "   $($actionTypeData.Type.Name): $($actionTypeData.Actions.Count) actions" -ForegroundColor Yellow
    } else {
        Write-Host "   $($actionTypeData.Type.Name): No actions found" -ForegroundColor Gray
    }
}
Write-Host "   Total: $($AllActionTypes | ForEach-Object { $_.Actions.Count } | Measure-Object -Sum).Sum actions" -ForegroundColor Green
Write-Host "🎯 Classes generated: HumanActions, HorseActions, ActionEnumExtensions, ActionUtils" -ForegroundColor Magenta